platform :ios, '10.0'

inhibit_all_warnings!

def utils
    pod 'SwiftGen', '5.2.1'
    pod 'SwiftLint', '0.29.4'
end

def common_pods
    utils
    pod 'SurfUtils/StringAttributes', :git => "https://github.com/surfstudio/iOS-Utils.git", :tag => "10.0.0"
    pod 'SurfUtils/CommonButton', :git => "https://github.com/surfstudio/iOS-Utils.git", :tag => "10.0.0"
    pod 'SPStorkController', '1.7.9'

    pod 'TextFieldsCatalog', :path => '../'
end

target 'TextFieldsCatalogExample' do
  use_frameworks!
  common_pods

  target 'TextFieldsCatalogExampleTests' do
    inherit! :search_paths
    common_pods
    pod 'iOSSnapshotTestCase', '6.2.0'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
