platform :ios, '10.0'

inhibit_all_warnings!

def utils
	pod 'SwiftGen', '~> 5.2.1'
    pod 'SwiftLint', '~> 0.29.1'
end

def common_pods
    utils
    pod 'SurfUtils/StringAttributes', :git => "https://github.com/surfstudio/iOS-Utils.git", :tag => "10.0.0"
    pod 'SurfUtils/CommonButton', :git => "https://github.com/surfstudio/iOS-Utils.git", :tag => "10.0.0"
    pod 'TextFieldsCatalog', :path => '../'
end

target 'TextFieldsCatalogExample' do
  use_frameworks!
  common_pods

  target 'TextFieldsCatalogExampleTests' do
    inherit! :search_paths
  end

end
