# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

prod_bundle_id = "surf.TextFieldsCatalog"
prod_scheme = "TextFieldsCatalog"
prod_target = "TextFieldsCatalog"

derived_data_path = "./buildData"

default_platform :ios

platform :ios do

  ENV["FASTLANE_HIDE_CHANGELOG"] = "true"
  ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"

  before_all do |lane, options|  
    # ensure_git_status_clean 
  end

  desc "Build Main scheme of Xcode target in Debug configuration"
  desc "Parameters:
  - clean: Pass **true** if you need to clean project before build
  "
  lane :build do |options|
    xcodebuild(
      scheme: prod_scheme,
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      destination: "generic/platform=iOS\" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\"",
      xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build-for-testing",
      derivedDataPath: derived_data_path
    )
  end

  desc "Run tests"
  lane :tests do
    run_tests(
      devices: ["iPhone SE"],
      scheme: prod_scheme,
      code_coverage: false,
      test_without_building: true,
      skip_build: true,
      derived_data_path: derived_data_path
  )
  end

end